### ISSUE TITLE
Key generation updates

### ISSUE THREAD

**Issue by vicsn** [summitto/pgp-key-generation#36]
Given the recommendations of our auditor we would like to make the following adjustments to the PGP library: 
- add a disclaimer in the README about the memory sanitization, on which platforms it will "probably" work and which will not. You can skim through the following material to hunt for possible information about guarantees: [CCC video](https://media.ccc.de/v/35c3-9788-memsad), [paper](https://proteancode.com/wp-content/uploads/2017/06/ae2017_final3_for_web.pdf).  
- We want to support two "modes" in the PGP application: (1) the seed comes out completely unencrypted. When this mode is chosen, a warning should first appear to the user that this might not be safe. (2) the seed comes out encrypted, with crypto_secretbox as noted in the audit. The result would be 90 chars base64 encoded: master_key (32) + salt (8) + mac (16) = 56 raw bytes.  
- a brief explanation in the README about the two "modes" and that the user should be careful with shouldertext for shoulder surfing

**Comment by omartijn** [comment]
I wonder about the first point, if memory sanitation does _not_ work on a specific platform, whatever PGP implementation is used (probably gnupg2) will also not support it. Should we feel responsible for warning the user about this? In case it doesn't work the user is probably complete SOL.

**Comment by vicsn** [comment]
> SOL 

TIL SOL

> Should we feel responsible for warning the user about this?

Well we indeed shouldn't have to note a list of e.g. a 100 platforms which we don't support. Perhaps we should write something more in the sense of: "memory sanitization is enabled as a defense-in-depth measure, but please do not depend on it because of caveats x, y and z".

**Comment by omartijn** [comment]
That was not exactly my point. The point is that if memory sanitation is not supported for a platform, it also means that using the key in gnupg2 is unsafe, so the problem is not limited to key generation.

Ideally you'd expect gnupg2 to warn users about this and we shouldn't be the ones to do this. I am wondering if it's a good idea to add such a warning, for two reasons:

- warning fatigue, when presented with too many warnings, people tend to zone out.
- lack of trust in pgp-key-generation: too many caveats, products feels "unsafe".

I'm not necessarily opposed to the idea of adding such a warning, I can understand the value of it. I just don't know whether that added value outweighs the downsides mentioned above.

**Comment by vicsn** [comment]
Valid points. I think a description in the README in a "warnings and caveats" section is fine, people can choose to skip that. Putting too many warnings inside the applications or dispersed through the text can be too taxing on the brain.

**Comment by rockhouse** [comment]
I have to agree with martijn here I also do not feel this is a good approach. If we cant protect why try in the first place? It might give a false sense of security. We follow this only because our Auditor feels "defence-in-depth" is more important than "warning fatigue" and "false sense of security". I think one can argue both ways. But we decided to follow that advice, so let's at least also limit the impact of the other two risks as much as possible.

**Comment by vicsn** [comment]
@rockhouse so in conclusion, no written warning about the limits of sanitization.

**Comment by rockhouse** [comment]
@vicsn there should be a warning but to _limit the impact_ maybe have (as I thought you also recommended) a general section on warnings & limitations.

**Comment by vicsn** [comment]
ACK, I thought you were disagreeing with my [latest point](https://github.com/summitto/pgp-key-generation/issues/36#issuecomment-566952270) but that's not the case then.

**Comment by vicsn** [comment]
@omartijn ping can you pick this up in the near future? Thank you!

**Comment by omartijn** [comment]
As previously discussed, it's on my list

**Comment by omartijn** [comment]
Looking at this issue a bit further, I notice that in the "encrypted mode" that is suggested, we don't add the encryption key to the output, but only the MAC and an 8-byte salt. Is this meant to suggest we generate the encryption key from the 8-byte salt?

I can't seem to open the audit report anymore, since it's password-protected and I don't have the passphrase.

**Comment by vicsn** [comment]
The auditor mentioned `crypto_secretbox(recovery_seed, master_key, generichash(salt), crypto_pwhash(recovery_seed_key, password, salt))` in chat, but as far as I see this implies having to back up a lot: recovery_seed + mac + recovery_seed_key + salt which is 88 bytes. I will ask the auditor for clarification.

**Comment by vicsn** [comment]
It seems there was a confusion, the correct version is:
`crypto_secretbox(recovery_seed, master_key, generichash(salt), crypto_pwhash(password, salt))`. With a unique salt for each password.
